<?php

return [
    'Elektronik',
    'Fashion & Pakaian',
    'Kesehatan & Kecantikan',
    'Makanan & Minuman',
    'Rumah Tangga',
    'Olahraga & Hobi',
    'Otomotif',
    'Buku & Alat Tulis',
    'Mainan & Games',
    'Perhiasan & Aksesoris',
    'Komputer & Laptop',
    'Handphone & Tablet',
    'Fotografi & Kamera',
    'Musik & Audio',
    'Tas & Sepatu',
    'Jam Tangan',
    'Perawatan Hewan',
    'Alat Pertukangan',
    'Bahan Makanan',
    'Peralatan Dapur',
    'Furnitur',
    'Dekorasi Rumah',
    'Alat Olahraga',
    'Sepeda & Aksesoris',
    'Alat Musik',
    'Hobi & Koleksi',
    'Alat Tulis Kantor',
    'Buku & Novel',
    'Komik & Manga',
    'Lainnya',
];

